enabled: true
entity_name: "VisReas-ETHZ" # Personal workspace is: klim-t
project_name: "compgen-reasoning"
run_name: null  # e.g. devrun
group: null  # e.g. "setting_1-experiment_1" (useful to group multiple runs with different seeds or hyperparameters)
tags: []
save_dir: ./wandb
log_model: false
