name: "trm_model"

# --- Architecture Constraints (computed in the Data Module) ---
max_h: ${data.max_h}  # one dimension of the grid, useful to calculate the grid size; e.g. for positional encoding and attention masking
max_w: ${data.max_w}  # one dimension of the grid, useful to calculate the grid size; e.g. for positional encoding and attention masking
max_task_seq_len: null  # length of the longest task sequence embeddings (i.e., the sequence of task tokens that describe the task)
max_seq_len: null   # set by dynamic max sequence length computation; will be updated to: (max_h * max_w) + total_special_tokens
total_seq_special_tokens_prepended: null  # total number of special tokens in the input sequence (e.g. task tokens + BOS)
total_seq_special_tokens_appended: null  # total number of special tokens appended to the input sequence (e.g. EOS)

pad_token_id: ${data.pad_token_id}

# --- Dimensions ---
# Inherit start value from data, but DataModule will overwrite this at runtime
input_vocab_size: ${data.vocab_size}  # this is the vocab size for the input embedding layer; it may be different from the output vocab size if we have special tokens that are only used in the input (e.g. task tokens) and that we do not want to predict
output_vocab_size: ${data.output_vocab_size}  # this is the vocab size for the output layer; it should be equal to the number of possible tokens that can appear in the grid we want to predict
output_dim: ${data.output_vocab_size}  # predicts logits (for the vocabulary, i.e. all possible tokens); this should be equal to output_vocab_size

d_model: 256  # input dimension; 128

dropout: 0.1

# --- Modeling techniques ---
use_task_tokens: true

ape:
  use_ape: false
  type: "learned"   # learned | 1d-sincos | 2d-sincos
  mixer: "sum"    # sum | learnable_scaling | weighted_sum | layer_norm | rms_norm

rpe:
  use_rpe: true
  type: "2d-rope"  # 1d-rope, 2d-rope

# Recursion
N_sup: 16   # maximum number of recursive steps over the same sample during training
trm_n: 6    # number of loops to updated the latent state within the latent recursion
trm_T: 3    # number of refinement loops (T-1 without gradients and 1 with gradients)

# Loss
loss_func: "cross_entropy"  # "cross_entropy" | "focal"
foreground_weight: 10.0     # weight for non-background cells (values 1-9) relative to background (0); set to 1.0 to disable
focal_gamma: 2.0            # down-weighting exponent for easy examples (only used when loss_func is set to "focal")
q_loss_weight: 0.5          # weight for the halting Q-node when calculating the total loss (reconstruction loss + q_loss)

# --- Optimization ---
optimizer: "adamw"  # "adamw" | "adam" | "sgd"
lr: 1e-4
embeddings_lr: 1e-2  # initial learning rate for the update of the input embeddings layer; set higher than the rest of the model to encourage faster learning of the input embeddings 
weight_decay: 1e-1

lr_scheduler:
  type: "cosine" # "cosine" | "step" | "plateau"
  interval: "epoch"  # 'epoch' or 'step'; whether to call the scheduler at epoch or training step
  frequency: 1  # how often to call the scheduler w.r.t. the interval
  monitored_metric: "val/id_loss"

lr_warmup:
  enabled: true
  type: "linear"
  num_steps: 200 # in TRM paper: 2000 steps
