max_epochs: 10
batch_size: 32
precision: "bf16-mixed" # use 16 for mixed precision training, 32 for full precision; "bf16-mixed"
gradient_clip_val: 1.0
accelerator: "gpu"

monitor_metric: "val/id_loss"
monitor_metric_mode: "min"
id_metric: "val/id_acc"
id_metric_mode: "max"
ood_metric: "val/ood_acc"
ood_metric_mode: "max"

early_stopping: true
patience: 10
save_top_k: 1

check_val_every_n_epoch: 1

accumulate_grad_batches: 1  # gradient accumulation; accumulate gradients over N batches before optimizer step (effective batch size = batch_size * accumulate_grad_batches)

num_workers: 4
devices: 1
