program: main.py
command:
  - uv
  - run
  - ${program}
  - ${args_no_hyphens}
  - model=trm_model
  - network/encoder=trm_encoder
  - network/decoder=trm_decoder
  - model.N_sup=8
  - model.trm_n=6
  - model.trm_T=3
  - data.use_ood_val=true
  - data.use_ood_test=true
  # - experiment.checkpoint_path=/cluster/raid/home/ktroyan/compgen-reasoning/outputs/2026-04-28/00-55-34/checkpoints/last.ckpt

method: grid

metric:
  name: val/id_loss
  goal: minimize

parameters:

  data.data_path:
    values:
    ### CompGen
    ## Setting 1
    # Subsetting 1
    - "hf://datasets/ktroyan/COGITAO/compgen/exp_setting_1-1/experiment_1_3M"
    - "hf://datasets/ktroyan/COGITAO/compgen/exp_setting_1-1/experiment_2_3M"
    # Subsetting 2
    - "hf://datasets/ktroyan/COGITAO/compgen/exp_setting_1-2/experiment_1_3M"
    # Subsetting 3
    - "hf://datasets/ktroyan/COGITAO/compgen/exp_setting_1-3/experiment_1_3M"
    - "hf://datasets/ktroyan/COGITAO/compgen/exp_setting_1-3/experiment_2_3M"
    # Subsetting 4
    - "hf://datasets/ktroyan/COGITAO/compgen/exp_setting_1-4/experiment_1_3M"
    # Subsetting 5
    - "hf://datasets/ktroyan/COGITAO/compgen/exp_setting_1-5/experiment_1_3M"
    - "hf://datasets/ktroyan/COGITAO/compgen/exp_setting_1-5/experiment_2_3M"
    - "hf://datasets/ktroyan/COGITAO/compgen/exp_setting_1-5/experiment_3_3M"
    ## Setting 2
    # Subsetting 1
    - "hf://datasets/ktroyan/COGITAO/compgen/exp_setting_2-1/experiment_1_3M"
    # Subsetting 2
    - "hf://datasets/ktroyan/COGITAO/compgen/exp_setting_2-2/experiment_1_3M"

    ### EnvGen
    # Setting 1
    - "hf://datasets/yassinetb/COGITAO/EnvGen/exp_setting_1/experiment_1"
    - "hf://datasets/yassinetb/COGITAO/EnvGen/exp_setting_1/experiment_2"
    - "hf://datasets/yassinetb/COGITAO/EnvGen/exp_setting_1/experiment_3"
    - "hf://datasets/yassinetb/COGITAO/EnvGen/exp_setting_1/experiment_4"
    - "hf://datasets/yassinetb/COGITAO/EnvGen/exp_setting_1/experiment_5"
    # Setting 2
    - "hf://datasets/yassinetb/COGITAO/EnvGen/exp_setting_2/experiment_1"
    - "hf://datasets/yassinetb/COGITAO/EnvGen/exp_setting_2/experiment_2"
    - "hf://datasets/yassinetb/COGITAO/EnvGen/exp_setting_2/experiment_3"
    - "hf://datasets/yassinetb/COGITAO/EnvGen/exp_setting_2/experiment_4"
    - "hf://datasets/yassinetb/COGITAO/EnvGen/exp_setting_2/experiment_5"
    # Setting 3 (which was 4 in the past)
    - "hf://datasets/yassinetb/COGITAO/EnvGen/exp_setting_4/experiment_1"
    - "hf://datasets/yassinetb/COGITAO/EnvGen/exp_setting_4/experiment_2"
    - "hf://datasets/yassinetb/COGITAO/EnvGen/exp_setting_4/experiment_3"
    - "hf://datasets/yassinetb/COGITAO/EnvGen/exp_setting_4/experiment_4"
    - "hf://datasets/yassinetb/COGITAO/EnvGen/exp_setting_4/experiment_5"

  training.max_epochs:
    values: [10]

  training.batch_size:
    values: [128]
  
  model.lr:
    values: [1e-5]

  # model.weight_decay:
  #   values: [1e-1, 1e-2]

  # model.lr_warmup.num_steps:
  #   values: [200]

  # network.encoder.num_layers:
    # values: [2, 4, 6]