program: main.py
command:
  - uv
  - run
  - ${program}
  - ${args_no_hyphens}
  - model.N_sup=4
  - model.trm_n=3
  - "data.data_path=hf://datasets/yassinetb/COGITAO/supplementary/Sample_Efficiency/exp_setting_3/experiment_1"
  - data.use_ood_val=false
  - data.use_ood_test=false

method: bayes

metric:
  name: val/id_loss
  goal: minimize

parameters:

  training.max_epochs:
    values: [10]

  training.batch_size:
    values: [32, 64]

  model.lr:
    values: [0.001, 0.0005, 0.0001]

  model.d_model:
    values: [128, 512]

  model.hidden_dim:
    values: [128, 256]
